version: '3.8'

# Development override for docker-compose.yml
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  hft-system:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./web:/app/web:ro
      - ./config:/app/config:ro
      # Keep data directories writable
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "8080:8080"
      - "9229:9229"  # Node.js debugger port
    
  # Lightweight services for development
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb
    
  mongodb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev-password
      
  influxdb:
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: dev-password
      DOCKER_INFLUXDB_INIT_ORG: dev-org
      DOCKER_INFLUXDB_INIT_BUCKET: dev-data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dev-token
